menu:
  display-settings:
    default:
      name: Default
server:
  port: 8082
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            mqtt:
              - uri: tcp://172.31.72.2:1883