menu:
  screens:
    - name: Test
      display-settings: default
      topic: BrickletLCD128x64/Test LCD
      default-view:
        display-value:
          - topic: control/clock
          - label: "Temp. Ist"
            topic: BrickletTemperature/Test Temp/temperature
            type: float
            format: 0.0째C
          - label: "Temp. Soll"
            topic: control/Test Temp/temp
            type: float
            format: 0.0째C
      root-menu:
        menu:
          - id: test
            label: Temperatur
            content:
              menu:
                - id: x2
                  label: t2
              display-value:
                - label: "Temp. Ist"
                  topic: BrickletTemperature/Test Temp/temperature
                  type: float
                  format: 0.0째C
                - label: "Temp. Soll"
                  topic: control/Test Temp/temp
                  type: float
                  format: 0.0째C

  display-settings:
    default:
      name: Default
server:
  port: 8082
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            mqtt:
              - uri: tcp://172.31.72.2:1883